// Auto-generated by Rove Reactive Systems Compiler (react - React 19 TSX)
import React, { useState, useEffect } from 'react';

export default function RoveApp() {
  const [title, setTitle] = useState(Alan Tarama UI);
  const [hz, setHz] = useState(5000);

  return (
    <div style={{ padding: 24, background: '#03060A', color: '#00F0FF', fontFamily: 'monospace' }}>
      <h1>Rove Reactive Engine</h1>
    </div>
  );
}
